### ISSUE TITLE
Request mapping to object

### ISSUE THREAD

**Issue by fesor** [fesor/request-objects#6]
Currently request object acts just like validator for arrays. It could be cool to use it nor just as request wrapper around payload. but as actual request object, which represents command for specific needs.

For example:

```php
use Fesor\RequestObject\Annotations\{RequestObject, Body, Header, Query};

/**
 * @RequestObject
 */
class RegisterUserCommand
{
     /**
       * @var string
       * @Body('first_name')
       */
     public $firstName;

     /**
       * @var string
       * @Body('last_name')
       */
     public $lastName;

     /**
       * @var string
       * @Body('email')
       */
     public $email;

     /**
       * @var string
       * @Query('usertype')
       */
     public $type;
}
```

Something like that.

**Comment by fesor** [comment]
Closing this issue since vision has been changed.

**Comment by sstalle** [comment]
@fesor Can you please elaborate? Why did you decide to ditch the idea of mapping to objects?

**Comment by fesor** [comment]
Hi, @sstalle.

Basically because I don't think that this would be good idea to provide some mapping abilities within this library. Also since Symfony already provides you argument resolvers which allows you to implement your own mappers.

Basicly what I really need right now is just validating http request data. Then you could just use argument resolvers to map this data to any object.
